AppConfig {
    general: GeneralConfig {
        rounded_corners: true,
        show_borders: true,
        highlight_symbol: Some(String::from(">> ")),
        favorite_symbol: Some(String::from("★ ")),
        favorite_key: Some(String::from("alt+f")),
        clipboard_command: None,
    },
    features: FeaturesConfig {
        enable_file_explorer: true,
        enable_launch_args: true,
        enable_auto_complete: true,
        dirs_first: true,
        show_duplicates: false,
        recent_first: true,
        symbol_search_trigger: String::from("."),
        replace_calc_symbols: false,
        fancy_numbers: false,
    },
    window: SectionConfig {
        title: None,
        fg: None,
        bg: Some(String::from("#000000")),
        border_color: None,
        rounded: None,
        borders: None,
        visible: Some(false),
        title_alignment: None,
    },
    outer_box: SectionConfig {
        title: Some(String::from(" Flare ")),
        fg: None,
        bg: None,
        border_color: Some(String::from("#cdd6f4")),
        rounded: None,
        borders: None,
        visible: Some(false),
        title_alignment: None,
    },
    flare_ascii: FlareAsciiConfig {
        section: SectionConfig {
            title: None,
            fg: None,
            bg: None,
            border_color: None,
            rounded: None,
            borders: None,
            visible: Some(true),
            title_alignment: None,
        },
        gradient: true,
        gradient_colors: vec![String::from("#6464ff"), String::from("#c864ff")],
        alignment: Some(TextAlignment::Center),
        padding: PaddingConfig {
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
        },
        custom_path: None,
    },
    input: SectionConfig {
        title: Some(String::from(" Search ")),
        fg: None,
        bg: None,
        border_color: Some(String::from("#cba6f7")),
        rounded: None,
        borders: None,
        visible: None,
        title_alignment: None,
    },
    results: ResultsConfig {
        section: SectionConfig {
            title: None,
            fg: None,
            bg: None,
            border_color: Some(String::from("#cba6f7")),
            rounded: None,
            borders: None,
            visible: None,
            title_alignment: None,
        },
        applications_title: None,
        directories_title: None,
        authentication_title: None,
    },
    entry_selected: SectionConfig {
        title: None,
        fg: Some(String::from("#1e1e2e")),
        bg: Some(String::from("#cba6f7")),
        border_color: None,
        rounded: None,
        borders: None,
        visible: None,
        title_alignment: None,
    },
    text: TextConfig {
        section: SectionConfig {
            title: None,
            fg: Some(String::from("#f2f5f7")),
            bg: None,
            border_color: None,
            rounded: None,
            borders: None,
            visible: None,
            title_alignment: None,
        },
        alignment: Some(TextAlignment::Left),
    },
}
